<?php

return [
    ['key' => 'additional_info', 'label' => 'Additional Info', 'description' => 'Extra information related to the order or shipment.'],
    ['key' => 'admin', 'label' => 'Admin', 'description' => 'Name or identifier of the admin responsible.'],
    ['key' => 'author_name', 'label' => 'Author Name', 'description' => 'Name of the author or content creator.'],
    ['key' => 'buyer_address', 'label' => 'Buyer Address', 'description' => 'Street address of the buyer.'],
    ['key' => 'buyer_city', 'label' => 'Buyer City', 'description' => 'City where the buyer is located.'],
    ['key' => 'buyer_country', 'label' => 'Buyer Country', 'description' => 'Country where the buyer resides.'],
    ['key' => 'buyer_name', 'label' => 'Buyer Name', 'description' => 'Full name of the buyer.'],
    ['key' => 'buyer_postal_code', 'label' => 'Buyer Postal Code', 'description' => 'Postal or ZIP code of the buyer’s address.'],
    ['key' => 'comment', 'label' => 'Comment', 'description' => 'Additional comment or note related to the order.'],
    ['key' => 'create_invoice_url', 'label' => 'Create Invoice Link', 'description' => 'Hyperlink used to initiate invoice creation.'],
    ['key' => 'currency', 'label' => 'Currency', 'description' => 'Currency code used for pricing (e.g., USD, EUR).'],
    ['key' => 'invoice_request_url', 'label' => 'Invoice Request URL', 'description' => 'Web address to request an invoice.'],
    ['key' => 'message', 'label' => 'Message', 'description' => 'Content of the message sent by the client or user.'],
    ['key' => 'order_details', 'label' => 'Order Details', 'description' => 'HTML table listing the order details.'],
    ['key' => 'payment_method', 'label' => 'Payment Method', 'description' => 'Chosen method for making the payment.'],
    ['key' => 'payment_method_url', 'label' => 'Payment Method URL', 'description' => 'URL related to the selected payment method.'],
    ['key' => 'post_url', 'label' => 'Post URL', 'description' => 'Link to the related post or product page.'],
    ['key' => 'product_list', 'label' => 'Product List', 'description' => 'List of products included in the order.'],
    ['key' => 'product_title', 'label' => 'Product Title', 'description' => 'Title or name of the product.'],
    ['key' => 'product_type', 'label' => 'Product Type', 'description' => 'Category or classification of the product.'],
    ['key' => 'receiver_first_name', 'label' => 'Receiver First Name', 'description' => 'First name of the receiving contact.'],
    ['key' => 'receiver_last_name', 'label' => 'Receiver Last Name', 'description' => 'Last name of the receiving contact.'],
    ['key' => 'reply_url', 'label' => 'Reply URL', 'description' => 'Link to respond to a message or offer.'],
    ['key' => 'request_invoice_url', 'label' => 'Request Invoice Link', 'description' => 'Link to request an invoice.'],
    ['key' => 'seller_address', 'label' => 'Seller Address', 'description' => 'Street address of the seller.'],
    ['key' => 'seller_city', 'label' => 'Seller City', 'description' => 'City where the seller is located.'],
    ['key' => 'seller_country', 'label' => 'Seller Country', 'description' => 'Country where the seller resides.'],
    ['key' => 'seller_name', 'label' => 'Seller Name', 'description' => 'Full name of the seller.'],
    ['key' => 'selling_price', 'label' => 'Selling Price', 'description' => 'Final price at which the product is sold.'],
    ['key' => 'shipping_price', 'label' => 'Shipping Price', 'description' => 'Cost incurred for shipping the product.'],
];
