<?php

return [
    ['key' => 'admin_firstname', 'label' => 'Admin First Name', 'description' => 'First name of the admin'],
    ['key' => 'admin_fullname', 'label' => 'Admin Full Name', 'description' => 'Full name of the admin'],
    ['key' => 'admin_lastname', 'label' => 'Admin Last Name', 'description' => 'Last name of the admin'],
    ['key' => 'admin_username', 'label' => 'Admin User Name', 'description' => 'ID of the admin'],
    ['key' => 'author_firstname', 'label' => 'Author First Name', 'description' => 'First name of the author.'],
    ['key' => 'author_fullname', 'label' => 'Author Full Name', 'description' => 'Full name of the author.'],
    ['key' => 'author_lastname', 'label' => 'Author Last Name', 'description' => 'Last name of the author.'],
    ['key' => 'buyer_address', 'label' => 'Buyer Address', 'description' => 'Street address of the buyer.'],
    ['key' => 'buyer_city', 'label' => 'Buyer City', 'description' => 'City where the buyer is located.'],
    ['key' => 'buyer_country', 'label' => 'Buyer Country', 'description' => 'Country where the buyer resides.'],
    ['key' => 'buyer_firstname', 'label' => 'Buyer First Name', 'description' => 'First name of the buyer.'],
    ['key' => 'buyer_fullname', 'label' => 'Buyer Full Name', 'description' => 'Full name of the buyer.'],
    ['key' => 'buyer_lastname', 'label' => 'Buyer Last Name', 'description' => 'Last name of the buyer.'],
    ['key' => 'buyer_postal_code', 'label' => 'Buyer Postal Code', 'description' => 'Postal or ZIP code of the buyer’s address.'],
    ['key' => 'buyer_username', 'label' => 'Buyer ID', 'description' => 'ID of the buyer.'],
    ['key' => 'comment', 'label' => 'Comment', 'description' => 'Additional comment or note related to the order.'],
    ['key' => 'create_invoice_url', 'label' => 'Create Invoice Link', 'description' => 'Hyperlink used to initiate invoice creation.'],
    ['key' => 'currency', 'label' => 'Currency', 'description' => 'Currency code used for pricing (e.g., USD, EUR).'],
    ['key' => 'invoice_request_url', 'label' => 'Invoice Request URL', 'description' => 'Web address to request an invoice.'],
    ['key' => 'logo_sm', 'label' => 'Logo Small', 'description' => 'Logo small (200x100)'],
    ['key' => 'logo_md', 'label' => 'Logo Medium', 'description' => 'Logo medium (300x150)'],
    ['key' => 'logo_lg', 'label' => 'Logo Large', 'description' => 'Logo large (400x200)'],
    ['key' => 'message', 'label' => 'Message', 'description' => 'Content of the message sent by the client or user.'],
    ['key' => 'order_details', 'label' => 'Order Details', 'description' => 'HTML table listing the order details.'],
    ['key' => 'payment_method', 'label' => 'Payment Method', 'description' => 'Chosen method for making the payment.'],
    ['key' => 'payment_method_url', 'label' => 'Payment Method URL', 'description' => 'URL related to the selected payment method.'],
    ['key' => 'post_url', 'label' => 'Post URL', 'description' => 'Link to the related post or product page.'],
    ['key' => 'product_list', 'label' => 'Product List', 'description' => 'List of products included in the order.'],
    ['key' => 'product_title', 'label' => 'Product Title', 'description' => 'Title or name of the product.'],
    ['key' => 'product_type', 'label' => 'Product Type', 'description' => 'Category or classification of the product.'],
    ['key' => 'receiver_firstname', 'label' => 'Receiver First Name', 'description' => 'First name of the receiving contact.'],
    ['key' => 'receiver_lastname', 'label' => 'Receiver Last Name', 'description' => 'Last name of the receiving contact.'],
    ['key' => 'receiver_username', 'label' => 'Receiver ID', 'description' => 'ID of the receiving contact.'],
    ['key' => 'receiver_fullname', 'label' => 'Receiver Full Name', 'description' => 'Full name of the receiving contact.'],
    ['key' => 'reply_url', 'label' => 'Reply URL', 'description' => 'Link to respond to a message or offer.'],
    ['key' => 'request_invoice_url', 'label' => 'Request Invoice Link', 'description' => 'Link to request an invoice.'],
    ['key' => 'seller_address', 'label' => 'Seller Address', 'description' => 'Street address of the seller.'],
    ['key' => 'seller_city', 'label' => 'Seller City', 'description' => 'City where the seller is located.'],
    ['key' => 'seller_country', 'label' => 'Seller Country', 'description' => 'Country where the seller resides.'],
    ['key' => 'seller_firstname', 'label' => 'Seller First Name', 'description' => 'First name of the seller.'],
    ['key' => 'seller_fullname', 'label' => 'Seller Full Name', 'description' => 'Full name of the seller.'],
    ['key' => 'seller_lastname', 'label' => 'Seller Last Name', 'description' => 'Last name of the buyer.'],
    ['key' => 'seller_username', 'label' => 'Seller ID', 'description' => 'ID of the seller.'],
    ['key' => 'selling_price', 'label' => 'Selling Price', 'description' => 'Final price at which the product is sold.'],
    ['key' => 'shipping_price', 'label' => 'Shipping Price', 'description' => 'Cost incurred for shipping the product.'],
    ['key' => 'user_firstname', 'label' => 'User First Name', 'description' => 'First name of the user'],
    ['key' => 'user_fullname', 'label' => 'User Full Name', 'description' => 'Full name of the user'],
    ['key' => 'user_lastname', 'label' => 'User Last Name', 'description' => 'Last name of the user'],
    ['key' => 'user_username', 'label' => 'User User Name', 'description' => 'ID of the user'],
];
